# Generated by Django 4.1.7 on 2023-03-19 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('other_titles', models.CharField(blank=True, max_length=60, null=True, verbose_name='Дополнительное название')),
                ('connect', models.CharField(blank=True, max_length=60, null=True, verbose_name='Что соединяет (долины)')),
                ('add_time', models.DateTimeField(verbose_name='Дата регистрации')),
                ('winter', models.CharField(blank=True, max_length=2, null=True, verbose_name='Категория трудности в зимний период')),
                ('summer', models.CharField(blank=True, max_length=2, null=True, verbose_name='Категория трудности в летний период')),
                ('autumn', models.CharField(blank=True, max_length=2, null=True, verbose_name='Категория трудности в осенний период')),
                ('spring', models.CharField(blank=True, max_length=2, null=True, verbose_name='Категория трудности в весенний период')),
                ('status', models.CharField(choices=[('new', 'новая запись'), ('pending', 'взято в работу'), ('accepted', 'успешная модерация'), ('rejected', 'информация отклонена')], default='new', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('height', models.PositiveIntegerField(verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20, unique=True, verbose_name='E-mail')),
                ('fam', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('otc', models.CharField(max_length=20, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=25, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('title', models.CharField(max_length=30, verbose_name='Название участка')),
                ('data', models.BinaryField(verbose_name='Изображение')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.add', verbose_name='Перевал')),
            ],
        ),
        migrations.AddField(
            model_name='add',
            name='coords',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.coords', verbose_name='Координаты'),
        ),
        migrations.AddField(
            model_name='add',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.users', verbose_name='Пользователь'),
        ),
    ]
